FROM tensorflow/tensorflow:latest

ADD . /src
WORKDIR /src
RUN python3 -m pip install --user -r requirements.txt

ENV INFERENCE_MODEL=/model.h5
ENV INFERENCE_CLASSES_FILE=/classes.txt
ENV INFERENCE_THRESHOLDS_FILE=/thresholds.csv

ENV INFERENCE_MINIMUM_THRESHOLD=0.5
ENV INFERENCE_PREPROCESS=inception_v3

ENV INPUT_HEIGHT=299
ENV INPUT_WIDTH=299
ENV INPUT_CHANNELS=3
ENV INPUT_BATCH=32

ENV SCHEDULER_FLUSH_INTERVAL=3.0
ENV SCHEDULER_QUEUE_SIZE=128

ENV SERVER_PORT=8001

ENTRYPOINT [ "python3" ]
CMD [ "server.py" ]